#!/bin/bash
# Assuming nginx webserver
yum install git gitweb fcgiwrap -y 

cat <</EOF > /var/www/nginx/conf.d/git.mydomain.tld
server {
  listen 4321; 
  server_name git.mydomain.tld;

  location /gitweb.cgi {
    root /var/www/git;
    include fastcgi_params;
    gzip off;
    fastcgi_param SCRIPT_NAME $uri;
    fastcgi_param GITWEB_CONFIG /etc/gitweb.conf;
    fastcgi_pass  unix:/var/run/fcgiwrap.socket;
  }

  location / {
    root /var/www/git;
    index gitweb.cgi;
  }
}
EOF

#Assuming this is done :
# su - $user
# mkdir ~/gitrepos/
# cd ~/gitrepos
# git init .
# echo "Changes made" > 1st_change.txt
# git add . 
# git commit -a "First Commit"
#

ln -s /home/$user/gitrepos/.git /var/lib/git/gitrepos.git

cd /var/lib/git
git clone --bare /home/$user/gitrepos/.git gitrepos.git
cd gitrepos.git
cp hooks/post-update.sample hooks/post-update
chmod a+x hooks/post-update
chown nobody: /var/run/fcgiwrap.socket
fcgiwrap -f -c2 -s unix:/var/run/fcgiwrap.socket

cat <<\EOF > /lib/systemd/system/fcgiwrap.service
[Unit]
Description=Perl FCGI server
After=syslog.target network.target remote-fs.target nss-lookup.target

[Service]
Type=forking
PIDFile=/var/run/fastcgiwrap.socket
ExecStartPre=/usr/sbin/fcgiwrap -f -c2 -s unix:/var/run/fastcgiwrap.socket
ExecStart=/usr/sbin/fcgiwrap
ExecReload=/usr/sbin/nginx -s reload
ExecStop=/bin/kill -s QUIT $MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF


service nginx restart
systemctl fcgiwrap enable
systemctl fcgiwrap start
netstat -tulpn | grep 4321
curl -I -L localhost:4321
